name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file # deployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: resourcegroup
          region: northeurope
          template: ./main.bicep
          parameters: "resourceGroupName=rg-arthur-ferket location=northeurope stSku=Basic"
          failOnStdErr: false

      - name: Validate the Bicep file
        run: az bicep build --file main.bicep
